# Generated by Django 4.2 on 2026-04-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('dominio', models.CharField(blank=True, max_length=200)),
                ('total_correos', models.IntegerField(default=0)),
                ('primer_contacto', models.DateTimeField(auto_now_add=True)),
                ('ultimo_contacto', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_uid', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de sincronización',
            },
        ),
        migrations.CreateModel(
            name='CorreoCopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('de', models.CharField(max_length=500)),
                ('para', models.TextField(blank=True)),
                ('asunto', models.CharField(blank=True, max_length=1000)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cuerpo', models.TextField(blank=True)),
                ('tiene_adjuntos', models.BooleanField(default=False)),
                ('nombres_adjuntos', models.TextField(blank=True)),
                ('uid_imap', models.IntegerField(db_index=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos', to='ModuloCorreos.perfilremitente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
