# Generated by Django 4.2 on 2026-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCorreos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaIMAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=200)),
                ('puerto', models.IntegerField(default=993)),
                ('usuario', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
