# Generated by Django 4.2 on 2026-04-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCorreos', '0002_cuentaimap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaimap',
            name='password',
        ),
    ]
