# Generated by Django 4.2 on 2026-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCorreos', '0003_remove_cuentaimap_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='correocopia',
            name='clasificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correocopia',
            name='resumen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='correocopia',
            name='tema',
            field=models.CharField(choices=[('factura', 'Factura / Cobranza'), ('soporte', 'Soporte / Consulta'), ('comercial', 'Comercial / Oferta'), ('notificacion', 'Notificación automática'), ('interno', 'Comunicación interna'), ('legal', 'Legal / Contrato'), ('spam', 'Spam'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='correocopia',
            name='tono',
            field=models.CharField(default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='clasificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='es_empresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='resumen_perfil',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='temas_frecuentes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='tono_predominante',
            field=models.CharField(choices=[('formal', 'Formal'), ('informal', 'Informal'), ('tecnico', 'Técnico'), ('comercial', 'Comercial'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
    ]
