# Generated by Django 4.2 on 2026-04-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCorreos', '0004_correocopia_clasificado_correocopia_resumen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('ley', 'Ley'), ('reglamento', 'Reglamento'), ('circular', 'Circular SII'), ('dictamen', 'Dictamen DT'), ('paper', 'Paper / Documento interno'), ('otro', 'Otro')], default='ley', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_legales/')),
                ('url', models.URLField(blank=True)),
                ('contenido', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='correocopia',
            name='es_pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='empresa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='frecuencia',
            field=models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('esporadica', 'Esporádica')], default='esporadica', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='nivel_prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='pendientes_activos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='rut',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('organismo_publico', 'Organismo Público'), ('interno', 'Interno'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='ultima_solicitud',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='correocopia',
            name='tema',
            field=models.CharField(choices=[('f29', 'F29 / IVA mensual'), ('f22', 'F22 / Renta anual'), ('ppm', 'PPM'), ('sii', 'SII / Timbre / RUT'), ('tgr', 'TGR / Tesorería'), ('inicio_termino_giro', 'Inicio / Término de giro'), ('contrato_trabajo', 'Contrato de trabajo'), ('finiquito', 'Finiquito'), ('despido', 'Despido / Desvinculación'), ('liquidacion_sueldo', 'Liquidación de sueldo'), ('licencia_medica', 'Licencia médica'), ('vacaciones', 'Vacaciones / Feriado'), ('accidente_laboral', 'Accidente laboral / Mutual'), ('direccion_trabajo', 'Dirección del Trabajo'), ('constitucion', 'Constitución de empresa'), ('modificacion', 'Modificación de estatutos'), ('poder_notarial', 'Poder notarial / Escritura'), ('balance', 'Balance / Estado financiero'), ('libro_contable', 'Libro diario / Mayor'), ('cuentas_cobrar', 'Cuentas por cobrar'), ('cuentas_pagar', 'Cuentas por pagar'), ('factura', 'Factura / Boleta'), ('nota_credito', 'Nota de crédito / débito'), ('certificado', 'Certificado'), ('declaracion_jurada', 'Declaración jurada'), ('tarea_urgente', 'Tarea urgente'), ('consulta', 'Consulta / Duda'), ('coordinacion', 'Coordinación / Reunión'), ('confirmacion', 'Confirmación / OK'), ('seguimiento', 'Seguimiento / Recordatorio'), ('notificacion_sii', 'Notificación SII'), ('notificacion_banco', 'Notificación banco'), ('notificacion_prevision', 'Notificación previsión'), ('spam', 'Spam / Publicidad'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
        migrations.AlterField(
            model_name='correocopia',
            name='tono',
            field=models.CharField(choices=[('formal', 'Formal'), ('informal', 'Informal'), ('tecnico', 'Técnico'), ('urgente', 'Urgente'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
    ]
