# Generated by Django 4.2 on 2026-04-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCorreos', '0005_documentolegal_correocopia_es_pendiente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=500)),
                ('para', models.TextField(blank=True)),
                ('asunto', models.CharField(blank=True, max_length=1000)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cuerpo', models.TextField(blank=True)),
                ('tiene_adjuntos', models.BooleanField(default=False)),
                ('nombres_adjuntos', models.TextField(blank=True)),
                ('uid_imap', models.IntegerField(db_index=True)),
                ('tema', models.CharField(blank=True, max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ParConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente_email', models.CharField(blank=True, max_length=200)),
                ('tema', models.CharField(blank=True, max_length=30)),
                ('es_respuesta', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('correo_enviado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pares_como_respuesta', to='ModuloCorreos.correoenviado')),
                ('correo_recibido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pares_como_solicitud', to='ModuloCorreos.correocopia')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
