# Generated by Django 4.2 on 2026-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCorreos', '0006_correoenviado_parconversacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilremitente',
            name='adjuntos_frecuentes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='contexto_ia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='palabras_clave_propias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='patron_dias_mes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='patron_dias_semana',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='respuesta_tipica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='tasa_adjuntos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='tiempo_respuesta_promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='perfilremitente',
            name='tipos_adjuntos_tema',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='correocopia',
            name='tema',
            field=models.CharField(choices=[('f29', 'F29 / IVA mensual'), ('f22', 'F22 / Renta anual'), ('ppm', 'PPM'), ('sii', 'SII / Timbre / RUT'), ('tgr', 'TGR / Tesorería'), ('inicio_termino_giro', 'Inicio / Término de giro'), ('contrato_trabajo', 'Contrato de trabajo'), ('finiquito', 'Finiquito'), ('renuncia', 'Renuncia voluntaria'), ('despido', 'Despido / Desvinculación'), ('liquidacion_sueldo', 'Liquidación de sueldo'), ('licencia_medica', 'Licencia médica'), ('vacaciones', 'Vacaciones / Feriado'), ('accidente_laboral', 'Accidente laboral / Mutual'), ('direccion_trabajo', 'Dirección del Trabajo'), ('constitucion', 'Constitución de empresa'), ('modificacion', 'Modificación de estatutos'), ('poder_notarial', 'Poder notarial / Escritura'), ('balance', 'Balance / Estado financiero'), ('libro_contable', 'Libro diario / Mayor'), ('cuentas_cobrar', 'Cuentas por cobrar'), ('cuentas_pagar', 'Cuentas por pagar'), ('rendicion', 'Rendición de gastos'), ('comprobante', 'Comprobante de pago'), ('factura', 'Factura / Boleta'), ('nota_credito', 'Nota de crédito / débito'), ('certificado', 'Certificado'), ('declaracion_jurada', 'Declaración jurada'), ('documento_trabajador', 'Documento de trabajador'), ('tarea_urgente', 'Tarea urgente'), ('consulta', 'Consulta / Duda'), ('coordinacion', 'Coordinación / Reunión'), ('confirmacion', 'Confirmación / OK'), ('seguimiento', 'Seguimiento / Recordatorio'), ('solicitud_fondos', 'Solicitud de fondos'), ('notificacion_sii', 'Notificación SII'), ('notificacion_banco', 'Notificación banco'), ('notificacion_prevision', 'Notificación previsión'), ('spam', 'Spam / Publicidad'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
    ]
